// PROFESSIONAL SCENE CONFIGURATION - ESSENTIAL SCENES ONLY
ADD_SCENE(predator, main_menu_clean, MainMenuClean)

// Car Security (CORE BUSINESS)
ADD_SCENE(predator, car_attacks_ui, CarAttacksUI)
ADD_SCENE(predator, car_model_selector, CarModelSelector)
ADD_SCENE(predator, car_test_results, CarTestResults)
ADD_SCENE(predator, car_tesla_ui, CarTeslaUI)
ADD_SCENE(predator, car_key_bruteforce_ui, CarKeyBruteforceUI)
ADD_SCENE(predator, car_jamming_ui, CarJammingUI)
ADD_SCENE(predator, car_passive_opener_ui, CarPassiveOpenerUI)

// WiFi Attacks (GOVERNMENT GRADE)
ADD_SCENE(predator, wifi_attacks_ui, WifiAttacksUI)
ADD_SCENE(predator, wifi_scan_ui, WifiScanUI)
ADD_SCENE(predator, wifi_deauth_ui, WifiDeauthUI)
ADD_SCENE(predator, wifi_evil_twin_ui, WifiEvilTwinUI)
ADD_SCENE(predator, wifi_handshake_ui, WifiHandshakeUI)
ADD_SCENE(predator, wifi_pmkid_ui, WifiPmkidUI)

// Bluetooth Attacks (ESSENTIAL)
ADD_SCENE(predator, bluetooth_attacks_ui, BluetoothAttacksUI)
ADD_SCENE(predator, ble_scan_ui, BleScanUI)
ADD_SCENE(predator, ble_spam_ui, BleSpamUI)

// RFID Attacks (ESSENTIAL)
ADD_SCENE(predator, rfid_attacks_ui, RfidAttacksUI)
ADD_SCENE(predator, rfid_clone_ui, RfidCloneUI)
ADD_SCENE(predator, rfid_bruteforce_ui, RfidBruteforceUI)
ADD_SCENE(predator, rfid_fuzzing_ui, RfidFuzzingUI)

// SubGHz Attacks (ESSENTIAL)
ADD_SCENE(predator, subghz_attacks_ui, SubGhzAttacksUI)
ADD_SCENE(predator, subghz_jamming_ui, SubGhzJammingUI)
ADD_SCENE(predator, subghz_raw_send_ui, SubGhzRawSendUI)

// System & Utility (ESSENTIAL)
ADD_SCENE(predator, module_status_ui, ModuleStatusUI)
ADD_SCENE(predator, board_selection_ui, BoardSelectionUI)
ADD_SCENE(predator, settings_ui, SettingsUI)
ADD_SCENE(predator, about_ui, AboutUI)
