// ULTIMATE SCENE CONFIGURATION - ALL FUNCTIONALITIES (No AI)
ADD_SCENE(predator, main_menu_ui, MainMenuUI)

// Tesla & Car Attacks (ALL Car Scenes)
ADD_SCENE(predator, car_tesla_ui, CarTeslaUI)
ADD_SCENE(predator, car_attacks_ui, CarAttacksUI)
ADD_SCENE(predator, car_key_bruteforce_ui, CarKeyBruteforceUI)
ADD_SCENE(predator, car_jamming_ui, CarJammingUI)
ADD_SCENE(predator, car_passive_opener_ui, CarPassiveOpenerUI)
ADD_SCENE(predator, car_model_selector, CarModelSelector)
ADD_SCENE(predator, car_model_tests, CarModelTests)
ADD_SCENE(predator, car_test_results, CarTestResults)
ADD_SCENE(predator, car_brand_security_suite, CarBrandSecuritySuite)
ADD_SCENE(predator, walking_open_ui, WalkingOpenUI)
ADD_SCENE(predator, universal_car_hacker, UniversalCarHacker)
ADD_SCENE(predator, tesla_security_suite, TeslaSecuritySuite)

// WiFi Attacks (ALL WiFi Scenes)
ADD_SCENE(predator, wifi_attacks_ui, WifiAttacksUI)
ADD_SCENE(predator, wifi_scan_ui, WifiScanUI)
ADD_SCENE(predator, wifi_deauth_ui, WifiDeauthUI)
ADD_SCENE(predator, wifi_evil_twin_ui, WifiEvilTwinUI)
ADD_SCENE(predator, wifi_handshake_ui, WifiHandshakeUI)
ADD_SCENE(predator, wifi_pmkid_ui, WifiPmkidUI)

// Bluetooth Attacks (ALL BLE Scenes)
ADD_SCENE(predator, bluetooth_attacks_ui, BluetoothAttacksUI)
ADD_SCENE(predator, ble_scan_ui, BleScanUI)
ADD_SCENE(predator, ble_spam_ui, BleSpamUI)

// RFID Attacks (ALL RFID Scenes)
ADD_SCENE(predator, rfid_attacks_ui, RfidAttacksUI)
ADD_SCENE(predator, rfid_clone_ui, RfidCloneUI)
ADD_SCENE(predator, rfid_bruteforce_ui, RfidBruteforceUI)
ADD_SCENE(predator, rfid_fuzzing_ui, RfidFuzzingUI)

// SubGHz Attacks (ALL SubGHz Scenes)
ADD_SCENE(predator, subghz_attacks_ui, SubGhzAttacksUI)
ADD_SCENE(predator, subghz_jamming_ui, SubGhzJammingUI)
ADD_SCENE(predator, subghz_raw_send_ui, SubGhzRawSendUI)

// GPS & Navigation (ALL GPS Scenes)
ADD_SCENE(predator, gps_tracker_ui, GpsTrackerUI)
ADD_SCENE(predator, wardriving_ui, WardrivingUI)

// Social Engineering
ADD_SCENE(predator, social_engineering_ui, SocialEngineeringUI)

// Government & Advanced Features (ALL Advanced)
ADD_SCENE(predator, traffic_light_security_ui, TrafficLightSecurityUI)
ADD_SCENE(predator, maximum_power, MaximumPower)
ADD_SCENE(predator, comprehensive_audit, ComprehensiveAudit)
ADD_SCENE(predator, enhanced_audit, EnhancedAudit)
ADD_SCENE(predator, system_audit, SystemAudit)
ADD_SCENE(predator, quick_poc, QuickPoc)
ADD_SCENE(predator, user_friendly_ui, UserFriendlyUI)

// System & Utility (ALL System Scenes)
ADD_SCENE(predator, module_status_ui, ModuleStatusUI)
ADD_SCENE(predator, board_selection_ui, BoardSelectionUI)
ADD_SCENE(predator, settings_ui, SettingsUI)
ADD_SCENE(predator, about_ui, AboutUI)
ADD_SCENE(predator, live_monitor_ui, LiveMonitorUI)
ADD_SCENE(predator, live_monitor, LiveMonitor)
